import MainNavigation from '../components/ui/MainNavigation';
import './globals.css';

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
			</head>
			<body>
				<header>
					<MainNavigation />
				</header>
				<main>{children}</main>
			</body>
		</html>
	);
}
